version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # Mount local files for hot reload
      - .:/app
      - /app/node_modules
    # Override CMD in dev mode
    command: npm run dev -- --host 0.0.0.0
